// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQeXX4SfV7e8TSEyUCVlkrs-PGPf3bHpM',
    appId: '1:831227271243:web:4d14854f0796abb01b55ce',
    messagingSenderId: '831227271243',
    projectId: 'flutter-testtutorial',
    authDomain: 'flutter-testtutorial.firebaseapp.com',
    storageBucket: 'flutter-testtutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo1lBt6Y0QNYrZNBoK8hOTFnOSeHgn-eo',
    appId: '1:831227271243:android:ec5961f4ca2aae451b55ce',
    messagingSenderId: '831227271243',
    projectId: 'flutter-testtutorial',
    storageBucket: 'flutter-testtutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYNsaz2FZMAadScp0ui_zQTSvux1t0G8',
    appId: '1:831227271243:ios:a69d19d63a255b351b55ce',
    messagingSenderId: '831227271243',
    projectId: 'flutter-testtutorial',
    storageBucket: 'flutter-testtutorial.appspot.com',
    iosBundleId: 'com.example.firebaseTask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYNsaz2FZMAadScp0ui_zQTSvux1t0G8',
    appId: '1:831227271243:ios:9b492305f1d359211b55ce',
    messagingSenderId: '831227271243',
    projectId: 'flutter-testtutorial',
    storageBucket: 'flutter-testtutorial.appspot.com',
    iosBundleId: 'com.example.firebaseTask1.RunnerTests',
  );
}
